#!/bin/bash
set -e

files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.ts')

for file in $files; do
  [ -f "$file" ] || continue # skip deleted files

  echo "checking - $file"
  # backup local copy
  backup=$(mktemp)
  cp "$file" "$backup"

  # restore file from staged
  git show ":$file" > "$file"

  # format
  bun format -- "$file"
  git add $file

  # restore and cleanup
  cp "$backup" "$file"
  rm "$backup"
done
