name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.13
      
      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test

      - name: Lint
        run: bun lint
      
      - name: Create build directory
        run: mkdir -p build
      
      - name: Build for macOS (Intel)
        run: bun build ./repl.ts --compile --target=bun-darwin-x64 --outfile=build/lisp-macos-x64
      
      - name: Build for macOS (Apple Silicon)
        run: bun build ./repl.ts --compile --target=bun-darwin-arm64 --outfile=build/lisp-macos-arm64
      
      - name: Build for Linux (x64)
        run: bun build ./repl.ts --compile --target=bun-linux-x64 --outfile=build/lisp-linux-x64
      
      - name: Build for Linux (ARM64)
        run: bun build ./repl.ts --compile --target=bun-linux-arm64 --outfile=build/lisp-linux-arm64
      
      - name: Build for Windows (x64)
        run: bun build ./repl.ts --compile --target=bun-windows-x64-modern --outfile=build/lisp-windows-x64.exe
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: build/
          retention-days: 7
      
      - name: Upload release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/lisp-macos-x64
            build/lisp-macos-arm64
            build/lisp-linux-x64
            build/lisp-linux-arm64
            build/lisp-windows-x64.exe