name: Build Binaries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  push-docs:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.13

      - name: Install dependencies
        run: bun install

      - name: Generate documentation
        run: >
          bun \
            --define __VERSION__="${{ needs.build.outputs.VERSION_STRING }}" \
            scripts/generate-docs.ts

      - name: Commit and push updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/docs.json docs/index.md
          git commit -m "chore(docs): update generated documentation for ${{ needs.build.outputs.VERSION_STRING }}"
          git push origin HEAD:main
      
      - name: Move release tag to docs commit
        run: |
          git fetch --tags
          git tag -f "${GITHUB_REF#refs/tags/}"
          git push --force origin "refs/tags/${GITHUB_REF#refs/tags/}"

  build:
    runs-on: ubuntu-latest
    outputs:
      VERSION_STRING: ${{ steps.version.outputs.VERSION_STRING }}
    strategy:
      matrix:
        build:
          - target: bun-darwin-x64
            outfile: lifp-darwin-amd64
          - target: bun-darwin-arm64
            outfile: lifp-darwin-arm64
          - target: bun-linux-x64
            outfile: lifp-linux-amd64
          - target: bun-linux-arm64
            outfile: lifp-linux-arm64
          - target: bun-windows-x64-modern
            outfile: lifp-windows-amd64.exe
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.13

      - name: Install dependencies
        run: bun install

      - name: Test
        run: bun test

      - name: Lint
        run: |
          chmod +x ./node_modules/@biomejs/cli-linux-x64/biome
          bun lint

      - name: Compute version string
        id: version
        run: |
          VERSION="${GITHUB_REF#refs/tags/}"
          [[ "$GITHUB_REF" != refs/tags/* ]] && VERSION="dev"
          VERSION_STRING="${VERSION} (${GITHUB_SHA:0:7})"
          echo "VERSION_STRING=$VERSION_STRING" >> $GITHUB_OUTPUT

      - name: Create build directory
        run: mkdir -p build

      - name: Generate documentation
        run: >
          bun \
            --define __VERSION__="${{ steps.version.outputs.VERSION_STRING }}" \
            scripts/generate-docs.ts

      - name: Build for ${{ matrix.build.target }}
        run: >
          bun build . \
            --compile \
            --target=${{ matrix.build.target }} \
            --outfile=build/${{ matrix.build.outfile }} \
            --define __VERSION__="${{ steps.version.outputs.VERSION_STRING }}"

      - name: Upload artifact for ${{ matrix.build.target }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.outfile }}
          path: build/
          retention-days: 7
      
      - name: Upload release assets
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/lifp-darwin-amd64
            build/lifp-darwin-arm64
            build/lifp-linux-amd64
            build/lifp-linux-arm64
            build/lifp-windows-amd64.exe